#!/bin/sh

pkgdir=/tmp/peanut/$pkg-$ver
src=$(pwd)
files=$(pwd)/files
out=/tmp/packages

jobs_fractor=1
num_cores=$(grep ^processor /proc/cpuinfo | wc -l)
jobs=$(($num_cores * $jobs_fractor))

pkg=glibc
ver=2.25
rel=1
desc="GNU C library."
wget_url="http://ftp.gnu.org/gnu/$pkg/$pkg-$ver.tar.xz"

prepare_env () {
  mkdir $pkgdir $out
  cd $src
  wget $wget_url
  tar -xvf $pkg-$ver.tar.xz
}

compile_pkg () {
    cd $src
    cd $pkg-$ver
    export CC="gcc"
    export CXX="g++"
    mkdir $pkg-build
    cd $pkg-build
    ../configure --prefix=/usr                     \
                 --libexecdir=/usr/lib             \
                 --with-headers=/usr/include       \
                 --mandir=/usr/share/man           \
                 --infodir=/usr/share/info         \
                 --enable-add-ons                  \
                 --enable-bind-now                 \
                 --enable-kernel=2.6.32            \
                 --enable-obsolete-rpc             \
                 --enable-stack-protector=strong   \
                 --without-cvs                     \
                 --without-gd                      \
                 --without-selinux                 \
                 --disable-profile                 \
                 --disable-werror                  \
                 --enable-stackguard-randomization \
                 --enable-lock-elision             \
                 --build=x86_64-peanut-linux       \
               libc_cv_slibdir=/lib                \
               CFLAGS="-O3 -g -fasynchronous-unwind-tables -DNDEBUG"
    make -j $jobs
    make install_root=$pkgdir install -j $jobs
    install -d $pkgdir/var/{db,run}/nscd
    cp -v ../nscd/nscd.conf $pkgdir/etc/nscd.conf
    install -d $pkgdir/usr/lib/{locale,systemd/system,tmpfiles.d}
    install -v -Dm644 ../nscd/nscd.tmpfiles $pkgdir$pkgdir/usr/lib/tmpfiles.d/nscd.conf
    install -v -Dm644 ../nscd/nscd.service $pkgdir/usr/lib/systemd/system/nscd.service
    install -m644 ../posix/gai.conf $pkgdir/etc/gai.conf
    install -m 0644 $src/ld.so.conf $pkgdir/etc
    install -d $pkgdir/etc/{default,ld.so.conf.d}
    rm -vf $pkgdir/sbin/sln
    rm -vf $pkgdir/usr/bin/rpcinfo
    rm -v $pkgdir/etc/ld.so.cache
    chmod 644 $pkgdir/lib/gconv/gconv-modules.cache
    rm -v $pkgdir/etc/localtime
    rm -rvf $pkgdir/usr/share/zoneinfo
    rm -v $pkgdir/usr/sbin/zdump
}

strip_pkg () {
  find $pkgdir -type f | xargs file | grep "LSB executable" | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
  find $pkgdir -type f | xargs file | grep "shared object" | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
  find $pkgdir -type f | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs strip -g 2> /dev/null || true
}

generate_pkg () {
  cd $pkg
  makepkg -l $out/$pkg-$ver-$rel.tlz
}

prepare_env
compile_pkg
strip_pkg
generate_pkg

exit 0
